name: Workflows, Jobs, and Steps

on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Groot - A (Java)"
      - run: echo "Groot - B (Python)"
      - run: echo "Groot - B (.NET)"
      - run: echo "Groot - B (PHP)"
  job-2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Multiple programming languages can be used in different jobs"
  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "The jobs can have dependencies on each other..."
  job-4:
    runs-on: ubuntu-24.04
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "...to form a directed acyclic graph (DAG)"
